import { useEffect, useState } from 'react';
<<<<<<< Updated upstream
import { household as sample, transactions as sampleTx, notice as sampleNotice } from '../data/household.sample.js';
import { parseNotice } from '../engine/changes.js';

const sampleHousehold = { ...sample, recurring: sample.recurring.map(bill => bill.id === 'internet' ? { ...bill, change: parseNotice(sampleNotice) } : bill) };

export function useHousehold() {
  const [state, set] = useState({ loading: import.meta.env.VITE_DATA_MODE === 'nessie', household: sampleHousehold, transactions: sampleTx, notice: sampleNotice, source: 'sample' });
  useEffect(() => {
    if (import.meta.env.VITE_DATA_MODE !== 'nessie') return;
    let active = true;
    fetch('/api/household').then(r => {
      if (!r.ok) throw new Error('Household unavailable');
      return r.json();
    }).then(d => {
      if (!d.household) throw new Error('Household unavailable');
      if (active) set({ loading: false, ...d });
    }).catch(() => {
      if (active) set(s => ({ ...s, loading: false, source: 'sample', notice: sampleNotice }));
    });
    return () => { active = false; };
  }, []);
=======
import { household as sampleHousehold, transactions as sampleTx, notice as sampleNotice } from '../data/household.sample.js';
import sampleSnapshot from '../data/nessie-snapshot.json';
import { discoverCommitments } from '../engine/discover.js';

// The sample file is generated by the same pipeline that serves live data (scripts/build-sample.mjs),
// so it carries the unexplained-charge flags but NOT the notice. A provider notice is not in a bank's
// records, so neither mode may start with one already applied to the forecast.
//
// Sample mode derives its proposals from the sample snapshot, exactly as the server derives live
// ones from live records. Neither mode ever shows the other's: live balances beside proposals drawn
// from a different household's spending would be worse than showing none.
const sampleDiscovered = discoverCommitments(sampleSnapshot, sampleHousehold);

// The same example, waiting rather than applied. Sample mode must not know something live mode
// only learns when the user accepts it.
const samplePending = [{
  id: 'example-internet',
  text: sampleNotice,
  origin: 'example',
  originLabel: 'Example notice included with this demo',
}];

const SAMPLE = {
  household: sampleHousehold,
  transactions: sampleTx,
  notice: sampleNotice,
  discovered: sampleDiscovered,
  pendingNotices: samplePending,
  source: 'sample',
};

export function useHousehold() {
  const [state, set] = useState({ loading: import.meta.env.VITE_DATA_MODE === 'nessie', ...SAMPLE });

  useEffect(() => {
    if (import.meta.env.VITE_DATA_MODE !== 'nessie') return;
    let active = true;

    fetch('/api/household')
      .then(r => { if (!r.ok) throw new Error('Household unavailable'); return r.json(); })
      .then(d => {
        if (!d.household) throw new Error('Household unavailable');
        // `discovered` comes from the server, computed against the same records as the household.
        if (active) set({ loading: false, discovered: [], pendingNotices: [], ...d });
      })
      .catch(() => {
        // Falling back means falling back completely: the sample household AND its own proposals.
        if (active) set({ loading: false, ...SAMPLE });
      });

    return () => { active = false; };
  }, []);

>>>>>>> Stashed changes
  return state;
}
