import { useEffect, useState } from 'react';
import { household as sampleHousehold, transactions as sampleTx, notice as sampleNotice } from '../../data/household.sample.js';
import sampleSnapshot from '../../data/nessie-snapshot.json';
import { discoverCommitments } from '../engine/discover.js';

// The sample file is generated by the same pipeline that serves live data (scripts/build-sample.mjs),
// so it already carries the parsed notice and the unexplained-charge flags. Nothing to patch here.
//
// Sample mode derives its proposals from the sample snapshot, exactly as the server derives live
// ones from live records. Neither mode ever shows the other's: live balances beside proposals drawn
// from a different household's spending would be worse than showing none.
const sampleDiscovered = discoverCommitments(sampleSnapshot, sampleHousehold);

const SAMPLE = {
  household: sampleHousehold,
  transactions: sampleTx,
  notice: sampleNotice,
  discovered: sampleDiscovered,
  source: 'sample',
};

export function useHousehold() {
  const [state, set] = useState({ loading: import.meta.env.VITE_DATA_MODE === 'nessie', ...SAMPLE });

  useEffect(() => {
    if (import.meta.env.VITE_DATA_MODE !== 'nessie') return;
    let active = true;

    fetch('/api/household')
      .then(r => { if (!r.ok) throw new Error('Household unavailable'); return r.json(); })
      .then(d => {
        if (!d.household) throw new Error('Household unavailable');
        // `discovered` comes from the server, computed against the same records as the household.
        if (active) set({ loading: false, discovered: [], ...d });
      })
      .catch(() => {
        // Falling back means falling back completely: the sample household AND its own proposals.
        if (active) set({ loading: false, ...SAMPLE });
      });

    return () => { active = false; };
  }, []);

  return state;
}
