import { useEffect, useState } from 'react';
import { household as sampleHousehold, transactions as sampleTx, notice as sampleNotice } from '../../data/household.sample.js';
import sampleSnapshot from '../../data/nessie-snapshot.json';

// The sample file is generated by the same pipeline that serves live data (scripts/build-sample.mjs),
// so it already carries the parsed notice and the unexplained-charge flags. Nothing to patch here.

export function useHousehold() {
  const [state, set] = useState({ loading: import.meta.env.VITE_DATA_MODE === 'nessie', household: sampleHousehold, transactions: sampleTx, notice: sampleNotice, snapshot: sampleSnapshot, source: 'sample' });
  useEffect(() => {
    if (import.meta.env.VITE_DATA_MODE !== 'nessie') return;
    let active = true;
    fetch('/api/household').then(r => {
      if (!r.ok) throw new Error('Household unavailable');
      return r.json();
    }).then(d => {
      if (!d.household) throw new Error('Household unavailable');
      if (active) set({ loading: false, snapshot: sampleSnapshot, ...d });
    }).catch(() => {
      if (active) set(s => ({ ...s, loading: false, source: 'sample', notice: sampleNotice }));
    });
    return () => { active = false; };
  }, []);
  return state;
}
