import { useCallback, useEffect, useRef, useState } from 'react';
import { household as sampleHousehold, transactions as sampleTx } from '../../data/household.sample.js';
import sampleSnapshot from '../../data/nessie-snapshot.json';
import { discoverCommitments } from '../engine/discover.js';

// The sample file is generated by the same pipeline that serves live data (scripts/build-sample.mjs),
// so it carries the unexplained-charge flags but NOT the notice. A provider notice is not in a bank's
// records, so neither mode may start with one already applied to the forecast.
//
// Sample mode derives its proposals from the sample snapshot, exactly as the server derives live
// ones from live records. Neither mode ever shows the other's: live balances beside proposals drawn
// from a different household's spending would be worse than showing none.
const sampleDiscovered = discoverCommitments(sampleSnapshot, sampleHousehold);

const SAMPLE = {
  household: sampleHousehold,
  transactions: sampleTx,
  notice: '',
  discovered: sampleDiscovered,
  pendingNotices: [],
  source: 'sample',
};

export function useHousehold() {
  const [state, set] = useState({ loading: import.meta.env.VITE_DATA_MODE === 'nessie', ...SAMPLE });
  const active = useRef(null);
  const refresh = useCallback(async () => {
    if (import.meta.env.VITE_DATA_MODE !== 'nessie') return false;
    active.current?.abort(); const controller = new AbortController(); active.current = controller;
    const timeout = setTimeout(() => controller.abort(), 20000);
    try {
      const response = await fetch('/api/household', { cache: 'no-store', signal: controller.signal });
      const data = await response.json();
      if (!response.ok || !data.household) throw new Error('Household unavailable');
      if (active.current === controller) set({ loading: false, error: '', discovered: [], pendingNotices: [], ...data });
      return true;
    } catch {
      // Never silently swap to a sample that leaves out the person's saved plans.
      if (active.current === controller) set(s => ({ ...s, loading: false,
        error: 'Your household or saved purchases couldn’t load. The forecast is paused so it won’t leave anything out.' }));
      return false;
    } finally { clearTimeout(timeout); }
  }, []);
  useEffect(() => { refresh(); return () => { const previous = active.current; active.current = null; previous?.abort(); }; }, [refresh]);
  return { ...state, refresh };
}
